# Generated by Django 4.0.5 on 2022-06-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('commands', models.IntegerField()),
                ('result', models.IntegerField()),
                ('duration', models.FloatField()),
            ],
        ),
    ]
