# Generated by Django 4.0.5 on 2022-06-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robot_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
